name: trapezoid
description: A customizable trapezoid/trapezium for Android, iOS, WEB, Linux, Mac and Windows.
version: 1.0.0
homepage: https://github.com/diogoroos/trapezoid

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.19.6 <4.0.0'
  flutter: ^3.12.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^3.0.0